
# num1=float(input("n1"))
# num2=float(input("n2"))
# num3=float(input("n3"))
# print(f"Soma:{num1+num2}")
# print(f"Sub:{num1-num2}")
# print(f"Mult:{num1*num2}")
# print(f"Div: {num1/num2}")
# print(f"Média: {(num1+num2+num3)/3}")
# mt = int(input("metros")); print(f"CENTÍMETROS: {mt*100}/ MILÍMETROS:{mt*1000}")
# retangulolarg=int(input("Largura"));retanguloalt=int(input("Altura"))
# print(f"AREA: {retangulolarg*retanguloalt}/ PERÍMETRO: {(retanguloalt*2)+(retangulolarg*2)}")
# raio=int(input("RAIO"));pi=3;print(f"DIAMETRO: {raio*2}/ CIRCUNFERÊNCIA: {2*pi*raio}/ AREA:{(raio**2)*pi}")
# preco=int(input("preço")); percentual = int(input("percentual"))
# precofinal= float(preco*float(1-(percentual*0.01)));print(precofinal)
# salant=int(input("salario")); percentual = int(input("percentual"))
# salfinal= int(salant*float(1+(percentual*0.01)));print(salfinal)
# kmperc=int(input("Km")); ltusado=int(input("Combustivel"))
# print(f"CONSUMO MEDIO: {round(ltusado/kmperc, 1)}litro por km")
# minuto = 60;hora = 60 * minuto;dia = (24 * hora);dias=int(input("DIAS"));horas=int(input("HORAS"));minutos=int(input("MINUTOS"))
# print(f"{dias} dia(s) tem {dias*dia} segundos, {horas} hora(s) tem {horas*hora} segundos, {minutos} minuto(s) tem {minutos*minuto}")
# num1=int(input("NUMERO"));num2=int(input("NUMERO"));print(f"a divisão entre {num1} e {num2} resulta em {num1//num2} e resta {num1%num2}")
