# num1=int(input("NUMERO"));num2=int(input("NUMERO"))
# if num1 !=num2: print(f"{num1} é diferente de {num2}.")
# if num1 > num2:print(f"{num1} é maior que {num2}.")
# if num1 < num2:print(f"{num2} é maior que {num1}.")
# if num1 == num2:print(f"{num2} e {num1} são iguais.")
# id=int(input("IDADE"))
# if id > 18: print("VOCÊ É MAIOR DE IDADE")
# else: print("VOCÊ É MENOR DE IDADE")
# num=int(input("NUMERO"))
# if 9 < num < 21:print("está entre 10 e 20")
# nota=int(input("NOTA"))
# if 0 <= nota < 11:print("PARABÉNS VOCÊ TIROU UMA NOTA ENTRE 0 E 10!")
# num1=int(input("NUMERO"));num2=int(input("NUMERO"))
# if num1 and num2 > 0:print("OS 2 SÃO POSITIVOS")
# num1=int(input("NUMERO"))
# if num1 > 0 and num1%2==0:print("PAR E POSITIVO")
# num1=int(input("NUMERO"));num2=int(input("NUMERO"));num3=int(input("NUMERO"))
# if num1 > num2 and num1 < num3:print("O PRIMEIRO É MAIOR Q O SEGUNDO, E MENOR Q O TERCEIRO")
nome=input("NOME"); senha=("SENHA")